# name: EAS Update on Main Push

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#     types: [closed]

# jobs:
#   update:
#     name: EAS Update
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#     if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18.x
#           cache: npm

#       - name: Setup EAS
#         uses: expo/expo-github-action@v8
#         with:
#           eas-version: latest
#           token: FPCIhesbuZsvpxQHTq5UoXToBe4ConUOj_oh8r8P

#       - name: Install dependencies
#         run: npm install

#       - name: Bump version
#         run: npm version patch --no-git-tag-version

#       - name: Create EAS update
#         env:
#           EXPO_TOKEN: FPCIhesbuZsvpxQHTq5UoXToBe4ConUOj_oh8r8P
#         run: eas update --branch preview --message "${{ github.event.head_commit.message }}"